// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table Users {
  id integer [primary key]
  username varchar [unique, not null]
  password varchar [not null]
  email varchar [unique, not null]
  firstName varchar [not null]
  lastName varchar [not null]
  isSuperuser boolean [default: false]
  lastLogin timestamp
  isActive boolean [default: true]
  createdAt timestamptz [not null, default: `now()`]
  updatedAt timestamptz [not null, default: `now()`]
  deletedAt timestamptz
}

Table Spectra {
  id integer [primary key]
  spectrumSamples JSON
  measurementDate timestamptz [not null]
  spectrumTypeId integer [not null]
  deviceId integer [not null]
  sampleId integer [not null]
  userId integer [not null]
  createdAt timestamptz [not null, default: `now()`]
  updatedAt timestamptz [not null, default: `now()`]
  deletedAt timestamptz

  Indexes {
    (spectrumTypeId)
    (deviceId)
    (sampleId)
    (userId)
  }
}

Table SpectraTypes {
  id integer [primary key]
  name varchar [not null]
  description varchar
  createdAt timestamptz [not null, default: `now()`]
  updatedAt timestamptz [not null, default: `now()`]
  deletedAt timestamptz
}

Table Samples {
  id integer [primary key]
  description varchar [not null]
  sampleCreationDate timestamptz
  coveredMaterialId integer [not null]
  coveringMaterialId integer [not null]
  createdAt timestamptz [not null, default: `now()`]
  updatedAt timestamptz [not null, default: `now()`]
  deletedAt timestamptz
  userId integer [not null]

  Indexes {
    (userId)
    (coveredMaterialId)
    (coveringMaterialId)
  }
}

Table CoveredMaterials {
  id integer [primary key]
  name varchar [not null]
  description varchar
  createdAt timestamptz [not null, default: `now()`]
  updatedAt timestamptz [not null, default: `now()`]
  deletedAt timestamptz
}

Table CoveringMaterials {
  id integer [primary key]
  name varchar [not null]
  description varchar
  manufacturer varchar [not null]
  color varchar [not null]
  createdAt timestamptz [not null, default: `now()`]
  updatedAt timestamptz [not null, default: `now()`]
  deletedAt timestamptz
}

Table SpectrumSimilarities {
  id integer [primary key]
  comparisonDate timestamptz [not null]
  similarity double [not null]
  baseSpectrumId integer [not null]
  comparedSpectrumId integer [not null]
  createdAt timestamptz [not null, default: `now()`]
  updatedAt timestamptz [not null, default: `now()`]
  deletedAt timestamptz

  Indexes {
    (baseSpectrumId, comparedSpectrumId) [unique]
  }
}

Table Devices {
  id integer [primary key]
  name varchar [not null]
  description varchar
  manufacturer varchar [not null]
  createdAt timestamptz [not null, default: `now()`]
  updatedAt timestamptz [not null, default: `now()`]
  deletedAt timestamptz
}

Ref: Spectra.userId > Users.id
Ref: Spectra.deviceId > Devices.id
Ref: Spectra.spectrumTypeId > SpectraTypes.id
Ref: Spectra.sampleId > Samples.id

Ref: SpectrumSimilarities.baseSpectrumId > Spectra.id
Ref: SpectrumSimilarities.comparedSpectrumId > Spectra.id

Ref: Samples.userId > Users.id
Ref: Samples.coveredMaterialId > CoveredMaterials.id
Ref: Samples.coveringMaterialId > CoveringMaterials.id
